### ISSUE TITLE
I get the following errors when I run the py script

### ISSUE THREAD

**Issue by asraghu123** [jeffreyrdcs/stock-vcpscreener#4]
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/cd00bd3a-1002-4eeb-9e6b-7764f78956b4)

Any guidance on how to fix it please ?

**Comment by asraghu123** [comment]
C:\Users\asraghu\VCP>pip list
Package                 Version
----------------------- ---------
aiohttp                 3.9.3
aiosignal               1.3.1
anyio                   3.6.1
appdirs                 1.4.4
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
asttokens               2.0.8
async-timeout           4.0.3
attrs                   23.2.0
Babel                   2.10.3
backcall                0.2.0
beautifulsoup4          4.12.3
bleach                  5.0.1
bs4                     0.0.2
cattrs                  22.2.0
certifi                 2024.2.2
cffi                    1.15.1
charset-normalizer      3.3.2
colorama                0.4.6
cssselect               1.2.0
cycler                  0.11.0
DateTime                5.4
debugpy                 1.6.3
decorator               5.1.1
defusedxml              0.7.1
Deprecated              1.2.14
entrypoints             0.4
exceptiongroup          1.1.0
exchange-calendars      4.2.4
executing               0.10.0
failstodeliver          0.0.5
fastjsonschema          2.16.1
finviz                  1.4.6
finvizfinance           0.14.7
fonttools               4.36.0
fpdf                    1.7.2
frozendict              2.4.0
frozenlist              1.4.1
html5lib                1.1
idna                    3.6
img2pdf                 0.5.1
importlib-metadata      4.12.0
ipykernel               6.15.1
ipython                 8.4.0
ipython-genutils        0.2.0
jedi                    0.18.1
Jinja2                  3.1.2
json5                   0.9.10
jsonschema              4.14.0
jupyter-client          7.3.4
jupyter-core            4.11.1
jupyter-server          1.18.1
jupyterlab              3.4.5
jupyterlab-pygments     0.2.2
jupyterlab-server       2.15.0
kiwisolver              1.4.4
korean-lunar-calendar   0.3.1
lxml                    4.9.4
MarkupSafe              2.1.1
matplotlib              3.5.3
matplotlib-inline       0.1.6
mistune                 0.8.4
mplfinance              0.12.10b0
multidict               6.0.5
multitasking            0.0.11
nbclassic               0.4.3
nbclient                0.6.6
nbconvert               6.5.3
nbformat                5.4.0
nest-asyncio            1.5.5
notebook                6.4.12
notebook-shim           0.1.0
numpy                   1.26.4
packaging               21.3
pandas                  2.2.1
pandas-datareader       0.10.0
pandas-market-calendars 4.1.3
pandocfilters           1.5.0
parso                   0.8.3
pdfmerger               0.5.0
peewee                  3.17.1
pickleshare             0.7.5
pikepdf                 8.13.0
pillow                  10.2.0
pip                     24.0
prometheus-client       0.14.1
prompt-toolkit          3.0.30
psutil                  5.9.1
pure-eval               0.2.2
pycparser               2.21
Pygments                2.13.0
pyluach                 2.0.2
pyparsing               3.0.9
PyPDF2                  3.0.1
pyrsistent              0.18.1
python-dateutil         2.8.2
pytz                    2024.1
pywin32                 304
pywinpty                2.0.7
pyzmq                   23.2.1
requests                2.31.0
requests-cache          0.9.7
scipy                   1.12.0
seaborn                 0.13.2
Send2Trash              1.8.0
setuptools              56.0.0
six                     1.16.0
sniffio                 1.2.0
soupsieve               2.5
stack-data              0.4.0
tenacity                8.2.3
terminado               0.15.0
tinycss2                1.1.1
toolz                   0.12.0
tornado                 6.2
tqdm                    4.66.2
traitlets               5.3.0
typing_extensions       4.10.0
tzdata                  2024.1
url-normalize           1.4.3
urllib3                 2.2.1
user-agent              0.1.10
wcwidth                 0.2.5
webencodings            0.5.1
websocket-client        1.3.3
wheel                   0.37.1
wrapt                   1.16.0
yarl                    1.9.4
yfinance                0.2.37
zipp                    3.8.1
zope.interface          6.2

**Comment by jeffreyrdcs** [comment]
I think it is exactly what the error says, the PyPDF2 3.0.1 version you have no longer have the PdfFileMerger class. I suppose you can either replace it with PdfMerger, or you can reinstall an older version of PyPDF2.

**Comment by asraghu123** [comment]
Thanks, that resolved the error.  Now I am facing with the classic python win32 file open error.  I have not opened the pdf files in any browser nor is anything like dropbox etc is active.   Any clue how to fix this ?   


![WhatsApp Image 2024-03-18 at 12 36 09_88c2a9dc](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/d40a3213-b14d-4a80-bd43-d6e1e9ede797)

**Comment by jeffreyrdcs** [comment]
Umm my suggestion would be to fetch the latest version of this repo and try again. The functions are now renamed from `gen_report_combine` to `generate_combined_pdf_report`, I also shuffled things around so it might have already fixed the issue. 

I don't have a Windows laptop so I can't try it myself, but I suspect it is due to me calling `os.remove` before I close the file. It would work on my mac but it may not work in windows due to file permission. Either way this is fixed in the refactor I just pushed to the repo.

If the issue is still there, make sure there are no multiple instances of your script running at the same time (or crashed before somewhere), then restart python and try again.

**Comment by asraghu123** [comment]
I downloaded the repo and ran again.  Now I think code is using for me in CST US time zone ;   03-17 and yahoo is saying no data. 
I change a statement to force the date to 03-18, still the same issue.   

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/6652aca1-098d-42c4-a6c1-0e57996c9e15)

**Comment by jeffreyrdcs** [comment]
I believe it is because the Update Index step failed, the code sees that the S&P500 index data is not updated.

The error `download() got an ....` seems to be an issue from the version of `pandas_datareader` you have. I suspect the newer version no longer have the pause keyword. You can try to remove this `pause=1` line inside `db.py` and try again:  https://github.com/jeffreyrdcs/stock-vcpscreener/blob/main/vcp_util/db.py#L88 

I also pushed a version with that line removed.

**Comment by asraghu123** [comment]
here are the versions of libraries installed on my pc
**_REQUIRED VERSIONS        MYVERSIONS_** 

mplfinance==0.12.7a17   
yfinance==0.1.63 
seaborn==0.11.1          ==> 0.13.2
img2pdf==0.4.1
pandas==1.0.3            ==>  2.2.1
matplotlib==3.2.1
numpy==1.19.5            ==>  1.26.4
requests==2.24.0         ==>  2.31.0
pandas_datareader==0.9.0 ==>   0.9.0 
fpdf==1.7.2
Pillow==8.3.1
PyPDF2==1.26.0

The error now I get is  

![WhatsApp Image 2024-03-19 at 10 05 52_6bffed6c](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/990d2d2a-e86a-47b7-b7b4-52babb4370ca)

**Comment by asraghu123** [comment]
I am unable to install the versions required for pandas and numpy.   the system throws a lot of dependencies error.  so I have no option but to install the latest version.  Is it possible to compile it with the latest versions of pandas and numpy and see if you get the same dataframe erropr

**Comment by asraghu123** [comment]
I have used the latest repo that you updated few mins ago

**Comment by asraghu123** [comment]
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/814b5a4d-6cf7-4f15-a9d7-2c1a7373519f)

I downloaded the repo into a new PC;  make sure t
[Tickers.csv](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14681015/Tickers.csv)
he requirements are as per the list.  and now I ran.  I get the pdf but there is nothing in it.    attaching the generated pdf.  pl let me know what might be the issue
[2024-03-19.pdf](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14681019/2024-03-19.pdf)
[selected_stock_2024-03-19.csv](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14681021/selected_stock_2024-03-19.csv)

**Comment by asraghu123** [comment]
Here is the list of packages and versions of the same installed in my new PC for reference. 
[my installed packages.txt](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14681100/my.installed.packages.txt)

**Comment by wilsonlam1** [comment]
@asraghu123 Hi, how to downgrade the pandas?

**Comment by asraghu123** [comment]
I tried to downgrade, but ran into problems, so I did a ground up install on a new PC which was a spare available for me.  Now I dont know why the reports and data are empty after successfully running it.  maybe @jeffreyrdcs  can help here.

**Comment by wilsonlam1** [comment]
@asraghu123 I see, let me try to find another PC to try it. Thanks!

BTW I also cannot generate all the reports and data. Let's wait for @jeffreyrdcs to fix it.

**Comment by jeffreyrdcs** [comment]
@asraghu123  I think yours ran successfully. I guess you only have one stock in ./db_yfinance/ so it is just checking if that particular stock met the criteria. To get all the stock data in `Ticker.csv`, you need to first fetch all the stock data. In this line in [`stock_vcpscreener.py` ](https://github.com/jeffreyrdcs/stock-vcpscreener/blob/main/stock_vcpscreener.py#L505) you can set `create=True` the first time to create all the stock files according to the `Ticker.csv`.

**Comment by jeffreyrdcs** [comment]
@asraghu123 @wilsonlam1 Yeah, I can try to update the old pandas operations at some point.

By the way, you don't need a separate PC to install the older versions of libraries (or older version of pythons). You can set up a virtual environment, for example using conda: https://conda.io/projects/conda/en/latest/user-guide/install/windows.html

This way you can have multiple python versions and different version of libraries on the same computer, each belongs to a different env. You can switch between the envs when you need them, or start clean when you need to install older version of python. It is way easier to deal with dependency issues that way!

**Comment by asraghu123** [comment]
@jeffreyrdcs @wilsonlam1   :   I set the statement svs.check_stock_database("yfinance", create=False, update=True)  # Use create=True flag to build stock files   as directed to create='True'.  This ran like a champ and absolute beauty it downloaded all the data for the SPX 500 tickers.  After that I ran with the flag set to 'False'. This beauty generated the pdf that is very good.  I have attached the pdf generated.   No issues at all.  
[2024-03-20.pdf](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14695706/2024-03-20.pdf)

I think this is a clean and good framework and implemented very methodically.  Maybe we should think of adding few things like FINRA short interest data (I might have some ideas which I will share).  

Again thanks for a beautiful scanner.

**Comment by asraghu123** [comment]
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/8a9502cc-82d1-4225-bf63-ccda2a02ce27)

**Comment by asraghu123** [comment]
here is the execution log.   maybe you can see if any improvements or issues/warnings 
[execution log.txt](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14696676/execution.log.txt)

Also attaching the DASH screen output sample for others

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/e43c76b7-8bf7-4fe7-9640-f5920f30baed)

**Comment by wilsonlam1** [comment]
> @jeffreyrdcs @wilsonlam1 : I set the statement svs.check_stock_database("yfinance", create=False, update=True) # Use create=True flag to build stock files as directed to create='True'. This ran like a champ and absolute beauty it downloaded all the data for the SPX 500 tickers. After that I ran with the flag set to 'False'. This beauty generated the pdf that is very good. I have attached the pdf generated. No issues at all. [2024-03-20.pdf](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14695706/2024-03-20.pdf)
> 
> I think this is a clean and good framework and implemented very methodically. Maybe we should think of adding few things like FINRA short interest data (I might have some ideas which I will share).
> 
> Again thanks for a beautiful scanner.

@asraghu123 
- Yes, it works to download all the tickers when changed to svs.check_stock_database("yfinance", create=False, update=True) # Use create=True flag 
- But I still cannot generate the report as below:
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/a6501f3d-b0db-41c5-ab6e-278ab6db4999)

**Comment by wilsonlam1** [comment]
> @asraghu123 @wilsonlam1 Yeah, I can try to update the old pandas operations at some point.
> 
> By the way, you don't need a separate PC to install the older versions of libraries (or older version of pythons). You can set up a virtual environment, for example using conda: https://conda.io/projects/conda/en/latest/user-guide/install/windows.html
> 
> This way you can have multiple python versions and different version of libraries on the same computer, each belongs to a different env. You can switch between the envs when you need them, or start clean when you need to install older version of python. It is way easier to deal with dependency issues that way!

@jeffreyrdcs @asraghu123 I just setup another version of the virtual environment via Anaconda by using Python 3.8 version to do below pip install:

mplfinance==0.12.7a17
[2024-03-21.pdf](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14718514/2024-03-21.pdf)

yfinance==0.1.63
seaborn==0.11.1
img2pdf==0.4.1
pandas==1.0.3
matplotlib==3.2.1
numpy==1.19.5
requests==2.24.0
pandas_datareader==0.9.0
fpdf==1.7.2
Pillow==8.3.1
PyPDF2==1.26.0

Finally I can run it!! Thank you so much! Here attached 2024-03-21 PDF.

**Comment by asraghu123** [comment]
closing the ticket as most issue are resolved.
